### ISSUE TITLE
_config file must have the url entry

### ISSUE THREAD

**Issue by keithmifsud** [keithmifsud/jekyll-target-blank#53]
In the documentation for jekyll-target-blank, you might want to add a note that "url="https://some.site.name/" must exist within the site's "_config.yml" file, otherwise it crashes when trying to compile with bundle (null value).

**Comment by rohandebsarkar** [comment]
When using [`github-metadata`](https://github.com/jekyll/github-metadata) plugin for extracting `site.url` from the GitHub repository for hosting with GitHub pages, this plugin crashes.

**Comment by peter1357908** [comment]
Bumping this. This is what caused the CloudFlare Pages build to fail: I didn't define `url` in `_config.yml` and the build would crash with an error whose root cause is as follows:
```
17:40:45.705 | /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/uri/rfc3986_parser.rb:15:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
-- | --
17:40:45.705 |  
17:40:45.706 | uri = uri.to_str
17:40:45.706 | ^^^^^^^
17:40:45.706 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/uri/rfc3986_parser.rb:71:in `parse'
17:40:45.706 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0/uri/common.rb:193:in `parse'
17:40:45.706 | from /opt/buildhome/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/jekyll-target-blank-2.0.2/lib/jekyll-target-blank.rb:196:in `external?'
```

The error went away after I added the production `url` to `_config.yml`. It even made the Preview deployment pass, which actually has a different `url` than the one I specified in `_config.yml`.

**Comment by keithmifsud** [comment]
Hi guys.

The URL in the config is required for this plugin to work.

Thanks
